version: '3.6'

services:
  db:
    image: postgres:11.4
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    # Docker hack to wait until postgres is up
    command: >
      bash -c "while ! nc -w 1 -z db 5432;
               do sleep 0.3;
               done;

               ./manage.py migrate;
               exec ./manage.py runserver 0.0.0.0:8000"
    image: oscarator
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/oscarator
