# Generated by Django 2.1.5 on 2019-02-03 20:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0003_auto_20190203_2056"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="vote", unique_together={("user", "entry")})
    ]
