# Generated by Django 2.1.5 on 2019-02-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0004_auto_20190203_2232")]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="imdb",
            field=models.CharField(blank=True, max_length=200, null=True),
        )
    ]
