# Generated by Django 2.1.5 on 2019-02-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0005_auto_20190204_0129")]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="is_winner",
            field=models.BooleanField(default=False),
        )
    ]
