# Generated by Django 2.1.5 on 2020-01-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0007_remove_category_year")]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="year",
            field=models.PositiveSmallIntegerField(default="2019"),
            preserve_default=False,
        )
    ]
