# Generated by Django 4.1.5 on 2023-01-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_category_options_alter_entry_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="year",
            field=models.PositiveSmallIntegerField(default=2023),
        ),
    ]
